// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mob struct {
	ID          pgtype.UUID
	Name        string
	WorldID     pgtype.UUID
	X           int32
	Y           int32
	Type        string
	Health      int32
	Attack      int32
	Defense     int32
	AttackSpeed int32
	Symbol      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Player struct {
	ID        pgtype.UUID
	WorldID   pgtype.UUID
	X         int32
	Y         int32
	Health    int32
	Attack    int32
	Defense   int32
	Range     int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type World struct {
	ID        pgtype.UUID
	Width     int32
	Height    int32
	Layout    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
